name: 'Package Pull Requests'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - 'packages/**'

jobs:
  build-pkg:
    name: Check that package builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: Get list of changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
                
      - name: Build Packages
        run: |
          PACKAGES=$(jq '.[]' -r ${HOME}/files.json | awk -F/ '{ print $2 "-" $3 }' | sort -u)
          echo "Packages: $PACKAGES"
          docker run -v "${{ github.workspace }}:/piston" docker.pkg.github.com/engineer-man/piston/repo-builder:latest --no-server $PACKAGES
          ls -la packages

      - name: Upload package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/*.pkg.tar.gz


  test-pkg:
    name: Test package
    runs-on: ubuntu-latest
    needs: build-pkg
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: packages
      
      - name: Relocate downloaded packages
        run: mv *.pkg.tar.gz packages/

      - name: Write test config file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: data/config.yaml
          contents: |
            log_level: DEBUG
            bind_address: 0.0.0.0:6969
            data_directory: /piston
            runner_uid_min: 1100
            runner_uid_max: 1500
            runner_gid_min: 1100
            runner_gid_max: 1500
            enable_unshare: false
            output_max_size: 1024
            max_process_count: 64
            max_open_files: 2048
            repo_url: http://localhost:8000/index

          write-mode: overwrite

      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: Run tests
        run: |
          ls -la
          docker run -v $(pwd)'/repo:/piston/repo' -v $(pwd)'/packages:/piston/packages' -d --name piston_fs_repo docker.pkg.github.com/engineer-man/piston/repo-builder --no-build
          docker run --network container:piston_fs_repo -v $(pwd)'/data:/piston' -d --name api docker.pkg.github.com/engineer-man/piston/api
          echo Waiting for API to start..
          docker run --network container:api appropriate/curl -s --retry 10 --retry-connrefused http://localhost:6969/runtimes

          echo Waiting for Index to start..
          docker run --network container:piston_fs_repo appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/index

          echo Adjusting index
          sed -i 's/piston_fs_repo/localhost/g' repo/index

          echo Listing Packages
          PACKAGES_JSON=$(docker run --network container:api appropriate/curl -s http://localhost:6969/packages)
          echo $PACKAGES_JSON

          echo Getting CLI ready
          docker run  -v "$PWD/cli:/app" --entrypoint /bin/bash node:15 -c 'cd /app; yarn'

          for package in $(jq -r '.[] | "\(.language)-\(.language_version)"' <<< "$PACKAGES_JSON")
          do
            echo "Testing $package"
            PKG_PATH=$(sed 's|-|/|' <<< $package)
            PKG_NAME=$(awk -F- '{ print $1 }' <<< $package)
            PKG_VERSION=$(awk -F- '{ print $2 }' <<< $package)

            echo "Installing..."
            docker run --network container:api appropriate/curl -sXPOST http://localhost:6969/packages/$PKG_PATH

            TEST_SCRIPTS=packages/$PKG_PATH/test.*
            echo "Tests: $TEST_SCRIPTS"

            for tscript in $TEST_SCRIPTS
            do
              TEST_RUNTIME=$(awk -F. '{print $2}' <<< $(basename $tscript))
              echo Running $tscript with runtime=$TEST_RUNTIME
              docker run --network container:api -v "$PWD/cli:/app" -v "$PWD/$(dirname $tscript):/pkg" node:15 /app/index.js run $TEST_RUNTIME $PKG_VERSION /pkg/$(basename $tscript) | grep OK
            done
          done


      - name: Dump logs
        if: ${{ always() }}
        run: |
          docker logs api
          docker logs piston_fs_repo








