name: Publish Repo image
on:
    push:
        branches:
            - master
            - v3
        paths:
            - repo/**

jobs:
    push_to_registry:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v2
            - name: Login to GitHub registry
              uses: docker/login-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com

            - name: Build and push repo
              uses: docker/build-push-action@v2
              with:
                  context: repo
                  pull: true
                  push: true
                  tags: |
                      docker.pkg.github.com/endercheif/piston/repo-builder
